Repository connect-foundation/2019-04, pull requests merged in 2019-11, with the labels that each got.

#92 [페어 프로그래밍] API server model
  api-server/Dockerfile
  api-server/Dockerfile.dev
  api-server/src/app.js
  api-server/src/models/File.js
  api-server/src/models/Project.js
  api-server/src/models/User.js
  api-server/src/models/index.js
Labels: DB, 👻BE

#95 Main page의 2번째 Section UI 구현
  cocode/src/components/GlobalStyle/index.js
  cocode/src/containers/AboutCocode/index.js
  cocode/src/containers/AboutCocode/style.js
Labels: 🌈FE

#96 Modal component 구현 & 로그인 버튼 클릭시 modal 출력
  cocode/package.json
  cocode/public/index.html
  cocode/src/components/CloseButton/close.svg
  cocode/src/components/CloseButton/index.js
  cocode/src/components/GlobalStyle/index.js
  cocode/src/components/LoginModalBody/index.js
  cocode/src/components/LoginModalBody/style.js
  cocode/src/components/Modal/index.js
  cocode/src/components/Modal/style.js
  cocode/src/components/Modal/test.js
  cocode/src/components/ModalPortal/index.js
  cocode/src/containers/Header/index.js
  cocode/src/containers/Header/test.js
  cocode/test_setup/__mocks__/fileMock.js
Labels: 🌈FE

#103 메인 페이지 디자인 다듬기
  cocode/src/components/GlobalStyle/index.js
  cocode/src/containers/AboutCocode/style.js
  cocode/src/containers/AboutUs/index.js
  cocode/src/containers/AboutUs/style.js
  cocode/src/containers/Header/style.js
  cocode/src/containers/Main/style.js
Labels: style, 🌈FE

#102 Browser component 구현
  cocode/src/components/Browser/BackwardButton/backward.svg
  cocode/src/components/Browser/BackwardButton/index.js
  cocode/src/components/Browser/ForwardButton/forward.svg
  cocode/src/components/Browser/ForwardButton/index.js
  cocode/src/components/Browser/ReloadButton/index.js
  cocode/src/components/Browser/ReloadButton/reload.svg
  cocode/src/components/Browser/index.js
  cocode/src/components/Browser/index.stories.js
  cocode/src/components/Browser/style.js
  cocode/src/constants/keyCode.js
  cocode/src/constants/theme.js
  cocode/src/containers/AboutCocode/index.js
  cocode/src/containers/AboutCocode/style.js
  cocode/src/containers/Header/index.js
  cocode/src/containers/Header/style.js
Labels: 🌈FE

#106 TabBar component 구현
  cocode/src/components/ProjectIcon/index.js
  cocode/src/components/ProjectIcon/style.js
  cocode/src/components/TabBar/index.js
  cocode/src/components/TabBar/style.js
  cocode/src/constants/theme.js
Labels: 🌈FE

#107 Project Tab Container 구현
  cocode/src/constants/theme.js
  cocode/src/containers/ProjectTab/index.js
  cocode/src/containers/ProjectTab/style.js
Labels: 🌈FE

#117 Project 페이지 기본 구조 구현
  cocode/src/components/Browser/index.js
  cocode/src/components/MonacoEditor/index.js
  cocode/src/components/TabBar/index.js
  cocode/src/components/TabBar/style.js
  cocode/src/containers/Editor/index.js
  cocode/src/containers/Editor/style.js
  cocode/src/containers/ProjectTab/style.js
  cocode/src/pages/Project/index.js
  cocode/src/pages/Project/style.js
Labels: 🌈FE

#133 메인 페이지 스크롤 기능 구현
  cocode/src/components/GlobalStyle/index.js
  cocode/src/components/ScrollDownButton/index.js
  cocode/src/components/ScrollDownButton/style.js
  cocode/src/components/ScrollTopButton/Arrow.svg
  cocode/src/components/ScrollTopButton/index.js
  cocode/src/components/ScrollTopButton/style.js
  cocode/src/containers/AboutCocode/index.js
  cocode/src/containers/AboutCocode/style.js
  cocode/src/containers/AboutUs/index.js
  cocode/src/containers/AboutUs/style.js
  cocode/src/containers/Header/index.js
  cocode/src/containers/Main/index.js
  cocode/src/containers/Main/style.js
  cocode/src/pages/Home/index.js
  cocode/src/utils/addWheelEvent.js
Labels: feature, style, 🌈FE

#137 [제안] Cocode history page 구현
  cocode/src/App.js
  cocode/src/components/GlobalStyle/index.js
  cocode/src/constants/theme.js
  cocode/src/containers/Header/index.js
  cocode/src/containers/Header/style.js
  cocode/src/containers/History/CocodeHistory/index.js
  cocode/src/containers/History/CocodeHistory/style.js
  cocode/src/pages/History/index.js
  cocode/src/pages/Version1/index.js
  cocode/src/pages/Version1/style.js
  cocode/src/pages/index.js
Labels: 🌈FE, 🗣suggestion

#140 대시보드 프로젝트 컨테이너 구현
  cocode/src/components/CreateCoconut/index.js
  cocode/src/components/CreateCoconut/index.stories.js
  cocode/src/components/CreateCoconut/style.js
  cocode/src/components/ProjectCard/index.js
  cocode/src/components/ProjectCard/style.js
  cocode/src/constants/theme.js
  cocode/src/containers/ProjectCardList/index.js
  cocode/src/containers/ProjectCardList/index.stories.js
  cocode/src/containers/ProjectCardList/style.js
Labels: 🌈FE

#141 스크롤 버그 수정
  cocode/src/components/Common/Modal/index.js
  cocode/src/components/Common/Modal/test.js
  cocode/src/components/Common/ModalPortal/index.js
Labels: 🌈FE, 🐛bug

#145 프로젝트 페이지 좌측 탭바 UI 구현
  cocode/src/components/Project/TabBar/dependency.svg
  cocode/src/components/Project/TabBar/explorer.svg
  cocode/src/components/Project/TabBar/index.js
  cocode/src/components/Project/TabBar/info.svg
  cocode/src/components/Project/TabBar/live.svg
  cocode/src/components/Project/TabBar/style.js
  cocode/src/components/Project/TabIcon/index.js
  cocode/src/components/Project/TabIcon/style.js
  cocode/src/constants/theme.js
Labels: style, 🌈FE

#148 Project page에 Split pane 적용
  cocode/package.json
  cocode/src/components/Common/SplitPane/LICENSE
  cocode/src/components/Common/SplitPane/Pane.js
  cocode/src/components/Common/SplitPane/Resizer.js
  cocode/src/components/Common/SplitPane/SplitPane.js
  cocode/src/components/Common/SplitPane/index.js
  cocode/src/containers/Project/Editor/style.js
  cocode/src/containers/Project/ProjectTab/style.js
  cocode/src/pages/Project/index.js
  cocode/src/pages/Version1/index.js
  cocode/yarn.lock
Labels: 🌈FE

#150 로그아웃 기능 구현
  cocode/src/constants/cookie.js
  cocode/src/containers/Common/Header/index.js
  cocode/src/utils/deleteCookie.js
Labels: feature, 🌈FE

#149 사용자별 프로젝트 목록을 조회하는 API를 구현
  api-server/package-lock.json
  api-server/package.json
  api-server/src/routes/users/controller.js
  api-server/src/routes/users/index.js
Labels: API, 👻BE

#152 API 요청 커스텀 훅 구현
  cocode/src/actions/API.js
  cocode/src/actions/types.js
  cocode/src/hooks/useFetch.js
  cocode/src/reducers/APIReducer.js
Labels: API, feature, 🌈FE

#155 fix: 500 에러 반환하는 프로젝트 목록 조회 API 에러 수정
  api-server/src/routes/users/controller.js
Labels: API, 🐛bug, 👻BE

#156 탐색기 탭에서 파일 이름 변경
  cocode/src/actions/Project.js
  cocode/src/actions/types.js
  cocode/src/components/Project/Directory/index.js
  cocode/src/components/Project/File/index.js
  cocode/src/components/Project/File/style.js
  cocode/src/constants/theme.js
  cocode/src/containers/Project/ExplorerTab/index.js
  cocode/src/containers/Project/ExplorerTab/style.js
  cocode/src/reducers/ProjectReducer.js
  cocode/src/utils/domControl.js
Labels: 🌈FE

#158 디펜던시 탭 컨테이너 UI 구현
  cocode/src/components/Project/DependencyItem/close.svg
  cocode/src/components/Project/DependencyItem/index.js
  cocode/src/components/Project/DependencyItem/style.js
  cocode/src/components/Project/DependencyNow/dummy.js
  cocode/src/components/Project/DependencyNow/index.js
  cocode/src/components/Project/DependencyNow/style.js
  cocode/src/components/Project/DependencySearch/dummy.js
  cocode/src/components/Project/DependencySearch/index.js
  cocode/src/components/Project/DependencySearch/style.js
  cocode/src/components/Project/DependencySearchItem/index.js
  cocode/src/components/Project/DependencySearchItem/style.js
  cocode/src/components/Project/DependencySelector/index.js
  cocode/src/components/Project/DependencySelector/style.js
  cocode/src/components/Project/GitHubLogo/index.js
  cocode/src/components/Project/GitHubLogo/style.js
  cocode/src/components/Project/MorelessButton/index.js
  cocode/src/components/Project/MorelessButton/style.js
  cocode/src/components/Project/NpmLogo/index.js
  cocode/src/components/Project/NpmLogo/style.js
  cocode/src/components/Project/PlusImage/index.js
  cocode/src/components/Project/PlusImage/style.js
  cocode/src/constants/theme.js
  cocode/src/containers/Project/Dependency/index.js
  cocode/src/containers/Project/Dependency/style.js
  cocode/src/containers/Project/DependencyTab/dummy.js
  cocode/src/containers/Project/DependencyTab/index.js
  cocode/src/containers/Project/DependencyTab/style.js
Labels: style, 🌈FE

#164 탐색기 탭 컨테이너 파일 생성 기능 구현
  cocode/src/actions/Project.js
  cocode/src/actions/types.js
  cocode/src/components/Project/Directory/index.js
  cocode/src/components/Project/File/index.js
  cocode/src/components/Project/File/style.js
  cocode/src/components/Project/NewFile/index.js
  cocode/src/components/Project/NewFile/style.js
  cocode/src/constants/fileImagesSrc.js
  cocode/src/constants/theme.js
  cocode/src/containers/Project/ExplorerTab/index.js
  cocode/src/containers/Project/ExplorerTab/style.js
  cocode/src/dummy/Project.js
  cocode/src/reducers/ProjectReducer.js
  cocode/src/utils/domControl.js
  cocode/src/utils/index.js
Labels: 🌈FE

#165 서버에 내 프로젝트 리스트 요청 기능 구현
  cocode/package.json
  cocode/src/apis/DashBoard.js
  cocode/src/components/DashBoard/ProjectCard/index.js
  cocode/src/components/DashBoard/ProjectCard/style.js
  cocode/src/config/index.js
  cocode/src/containers/DashBoard/ProjectCardList/index.js
  cocode/src/contexts/DashBoardContext.js
  cocode/src/contexts/index.js
  cocode/src/pages/DashBoard/index.js
  cocode/yarn.lock
Labels: feature, 🌈FE

#166 user context 생성
  cocode/src/App.js
  cocode/src/apis/User.js
  cocode/src/containers/Common/Header/index.js
  cocode/src/containers/Common/Header/test.js
  cocode/src/contexts/UserContext.js
  cocode/src/hooks/useFetch.js
Labels: feature, 🌈FE

#167 api 통신 시 데이터 전송에 대한 컨벤션을 적용
  api-server/src/routes/users/controller.js
Labels: API, 👻BE

#168 드롭다운 스타일 변경 및 핸들러 추가
  cocode/src/components/Common/DropDownMenu/style.js
  cocode/src/components/Common/GlobalStyle/index.js
  cocode/src/constants/theme.js
  cocode/src/containers/Common/Header/index.js
Labels: style, 🌈FE

#170 탭 컨테이너와 탭바 연동
  cocode/src/components/Project/Dependency/index.js
  cocode/src/components/Project/Dependency/style.js
  cocode/src/components/Project/DependencyItem/style.js
  cocode/src/components/Project/DependencySearch/style.js
  cocode/src/components/Project/DependencySearchItem/style.js
  cocode/src/components/Project/MorelessButton/style.js
  cocode/src/constants/theme.js
  cocode/src/containers/Project/DependencyTab/index.js
  cocode/src/containers/Project/ExplorerTab/index.js
  cocode/src/containers/Project/ExplorerTab/style.js
  cocode/src/containers/Project/InfoTab/index.js
  cocode/src/containers/Project/InfoTab/style.js
  cocode/src/containers/Project/TabBar/dependency.svg
  cocode/src/containers/Project/TabBar/explorer.svg
  cocode/src/containers/Project/TabBar/index.js
  cocode/src/containers/Project/TabBar/info.svg
  cocode/src/containers/Project/TabBar/live.svg
  cocode/src/containers/Project/TabBar/style.js
  cocode/src/containers/Project/TabContainer/index.js
  cocode/src/containers/Project/TabContainer/style.js
  cocode/src/pages/Project/index.js
Labels: feature, 🌈FE
