Repository connect-foundation/2019-04, pull requests merged in 2019-12, with the labels that each got.

#186 테마 오탈자 수정
  cocode/src/components/DashBoard/ProjectCard/style.js
  cocode/src/components/Project/Browser/index.js
  cocode/src/components/Project/Browser/style.js
  cocode/src/constants/theme.js
  cocode/src/containers/Common/Header/style.js
  cocode/src/pages/Version1/style.js
Labels: style, 🌈FE

#169 프로젝트 정보를 수정하는 API 를 구현했습니다.
  api-server/package-lock.json
  api-server/package.json
  api-server/src/app.js
  api-server/src/config/index.js
  api-server/src/routes/index.js
  api-server/src/routes/projects/controller.js
  api-server/src/routes/projects/index.js
Labels: API, 👻BE

#187 파일 탭바에 상태 적용
  cocode/src/components/Project/FileTab/index.js
  cocode/src/components/Project/FileTab/style.js
  cocode/src/components/Project/FileTabBar/index.js
  cocode/src/components/Project/FileTabBar/style.js
  cocode/src/components/Project/MonacoEditor/index.js
  cocode/src/components/Project/MonacoEditor/style.js
  cocode/src/constants/theme.js
  cocode/src/reducers/ProjectReducer.js
Labels: feature, 🌈FE

#188 info 탭 컨테이너 스타일 수정
  cocode/src/constants/theme.js
  cocode/src/containers/Project/InfoTab/index.js
  cocode/src/containers/Project/InfoTab/style.js
Labels: style, 🌈FE

#190 대시보드 영역에 스크롤 속성 추가
  cocode/src/containers/DashBoard/ProjectCardList/style.js
Labels: style, 🌈FE

#192 대시보드 초기 사용자 프로젝트 목록 조회 API 요청 구현
  cocode/src/contexts/index.js
  cocode/src/hooks/useFetch.js
  cocode/src/pages/DashBoard/index.js
Labels: feature, 🌈FE

#198 탐색기 탭에서 파일 삭제 기능 구현
  cocode/src/actions/Project.js
  cocode/src/actions/types.js
  cocode/src/components/Project/Directory/index.js
  cocode/src/components/Project/File/index.js
  cocode/src/components/Project/FileTabBar/index.js
  cocode/src/containers/Project/ExplorerTab/index.js
  cocode/src/dummy/Project.js
  cocode/src/reducers/ProjectReducer.js
Labels: feature, 🌈FE

#197 로그인시 user 데이터를 db에 조회 또는 생성
  api-server/database/seeds/user.seed.js
  api-server/src/config/index.js
  api-server/src/middlewares/passport.js
  api-server/src/routes/users/login/controller.js
Labels: API, 👻BE

#201 대시보드 페이지 이름 변경 및 삭제 상태관리 및 서버연동
  cocode/src/actions/API.js
  cocode/src/actions/Dashboard.js
  cocode/src/actions/types.js
  cocode/src/apis/DashBoard.js
  cocode/src/components/Common/DropDownMenu/index.js
  cocode/src/components/DashBoard/ProjectCard/index.js
  cocode/src/components/DashBoard/ProjectCard/style.js
  cocode/src/hooks/useFetch.js
  cocode/src/pages/DashBoard/index.js
  cocode/src/reducers/APIReducer.js
  cocode/src/reducers/DashboardReducer.js
Labels: feature, 🌈FE

#205 프로젝트 에디터 이동 기능 구현
  cocode/src/App.js
  cocode/src/components/Common/DropDownMenu/index.js
  cocode/src/components/DashBoard/ProjectCard/index.js
  cocode/src/containers/Common/Header/index.js
  cocode/src/containers/DashBoard/ProjectCardList/index.js
  cocode/src/containers/Home/Main/index.js
Labels: feature, 🌈FE

#207 프로젝트 정보 가져오는 API 구현
  api-server/database/seeds/contents.template.js
  api-server/database/seeds/file.seed.js
  api-server/database/seeds/project.seed.js
  api-server/database/seeds/user.seed.js
  api-server/src/models/File.js
  api-server/src/routes/projects/controller.js
  api-server/src/routes/projects/index.js
Labels: feature, 👻BE

#210 fix: 프로젝트 정보 변경 api 수정
  api-server/src/routes/projects/controller.js
Labels: API, 👻BE

#211 파일 생성, 수정, 삭제 API 구현
  api-server/package-lock.json
  api-server/package.json
  api-server/src/routes/projects/controller.js
  api-server/src/routes/projects/files/controller.js
  api-server/src/routes/projects/files/index.js
  api-server/src/routes/projects/index.js
  api-server/src/utils/transaction.js
Labels: API, 👻BE

#213 프로젝트 페이지 이동시 프로젝트 정보 가져오는 기능 구현
  cocode/.eslintignore
  cocode/package.json
  cocode/src/actions/types.js
  cocode/src/apis/Project.js
  cocode/src/pages/Project/index.js
  cocode/src/pages/Version1/index.js
  cocode/src/reducers/APIReducer.js
  cocode/src/template/objectIdMapper.js
  cocode/src/template/react.js
  cocode/yarn.lock
Labels: feature, 🌈FE

#218 파일 삭제 API 요청 로직 구현
  cocode/src/apis/File.js
  cocode/src/components/Project/Directory/index.js
  cocode/src/components/Project/File/index.js
  cocode/src/components/Project/NewFile/index.js
  cocode/src/containers/Project/ExplorerTab/index.js
Labels: feature, 🌈FE

#217 디펜던시 검색 라우터 구현
  api-server/database/seeds/file.seed.js
  api-server/database/seeds/project.seed.js
  api-server/package-lock.json
  api-server/package.json
  api-server/src/routes/dependency/controller.js
  api-server/src/routes/dependency/index.js
  api-server/src/routes/index.js
Labels: API, 👻BE

#219 프로젝트 페이지 디펜던시 탭 컨테이너 검색 결과 노출
  cocode/src/apis/Project.js
  cocode/src/components/Project/DependencySearch/index.js
  cocode/src/components/Project/DependencySearch/style.js
  cocode/src/components/Project/DependencySearchItem/index.js
  cocode/src/config/index.js
Labels: feature, 🌈FE

#220 프로젝트 포크 API 라우터 구현
  api-server/src/routes/projects/controller.js
  api-server/src/routes/projects/index.js
Labels: API, 👻BE

#221 프로젝트 페이지에서 서버에 프로젝트 생성 요청 구현
  cocode/src/apis/Project.js
  cocode/src/pages/Project/index.js
Labels: feature, 🌈FE

#223 파일수정 API 클라이언트에 적용
  cocode/src/apis/File.js
  cocode/src/components/Project/Directory/index.js
  cocode/src/components/Project/File/index.js
  cocode/src/components/Project/MonacoEditor/index.js
  cocode/src/containers/Project/Editor/index.js
Labels: feature, 🌈FE

#224 cocode 초기화 스크립트 작성
  cocode/.eslintignore
  cocode/Dockerfile
  cocode/Dockerfile.dev
  cocode/init-script/entry-plugin.js
  cocode/init-script/get-module-list-for-target-version.js
  cocode/init-script/index.js
  cocode/init-script/normalize-options.js
  cocode/init-script/usage-plugin.js
  cocode/package.json
  cocode/src/components/Project/BrowserV2/index.js
  cocode/src/components/Project/BrowserV2/style.js
  cocode/src/components/Project/Directory/index.js
Labels: 🌈FE

#226 dependency-packager 모듈 요청 및 bundler 리팩토링
  cocode/public/index.html
  cocode/src/actions/Project.js
  cocode/src/actions/types.js
  cocode/src/apis/Dependency.js
  cocode/src/bundler/core.js
  cocode/src/bundler/global.js
  cocode/src/bundler/index.js
  cocode/src/bundler/pathParser.js
  cocode/src/bundler/require.js
  cocode/src/components/Project/BrowserV1/index.js
  cocode/src/components/Project/BrowserV2/index.js
  cocode/src/components/Project/DependencyItem/index.js
  cocode/src/components/Project/DependencyNow/index.js
  cocode/src/components/Project/DependencySearchItem/index.js
  cocode/src/components/Project/PlusImage/index.js
  cocode/src/config/index.js
  cocode/src/reducers/ProjectReducer.js
Labels: Refactoring, feature, 🌈FE

#229 1.1.1 배포를 위한 api server 재시도!
  api-server/Dockerfile
  api-server/ecosystem.config.js
  api-server/package.json
Labels: 배포💥

#240 V1.2.0 최적화
  cocode/src/actions/Project.js
  cocode/src/actions/types.js
  cocode/src/apis/Project.js
  cocode/src/bundler/pathParser.js
  cocode/src/bundler/require.js
  cocode/src/components/Common/CoconutSpinner/index.js
  cocode/src/components/Common/CoconutSpinner/style.js
  cocode/src/components/Common/TinyCoconutLogo/index.js
  cocode/src/components/Project/BrowserV2/index.js
  cocode/src/components/Project/BrowserV2/style.js
  cocode/src/components/Project/Dependency/style.js
  cocode/src/components/Project/DependencySearch/index.js
  cocode/src/components/Project/DependencySearch/style.js
  cocode/src/components/Project/DependencySearchItem/index.js
  cocode/src/components/Project/Directory/index.js
  cocode/src/components/Project/File/index.js
  cocode/src/containers/Project/DependencyTab/index.js
  cocode/src/containers/Project/DependencyTab/style.js
  cocode/src/containers/Project/Editor/index.js
  cocode/src/hooks/useFetch.js
  cocode/src/pages/Project/index.js
  cocode/src/reducers/ProjectReducer.js
Labels: 🌈FE

#244 배포환경에 따른 passport client option 분리
  api-server/dev.env
  api-server/src/config/index.js
  api-server/src/middlewares/passport.js
Labels: 👻BE

#245 라이브 탭 컨테이너 UI 및 상태관리 토대 작성
  cocode/src/actions/Live.js
  cocode/src/actions/types.js
  cocode/src/components/Project/LiveUserProfile/index.js
  cocode/src/components/Project/LiveUserProfile/style.js
  cocode/src/constants/theme.js
  cocode/src/containers/Project/LiveTab/LiveOff.js
  cocode/src/containers/Project/LiveTab/LiveOn.js
  cocode/src/containers/Project/LiveTab/index.js
  cocode/src/containers/Project/LiveTab/style.js
  cocode/src/containers/Project/TabBar/index.js
  cocode/src/containers/Project/TabContainer/index.js
  cocode/src/contexts/LiveContext.js
  cocode/src/contexts/index.js
  cocode/src/pages/Project/index.js
  cocode/src/reducers/LiveReducer.js
  cocode/src/reducers/index.js
  cocode/src/stores/LiveStore.js
  cocode/src/stores/index.js
Labels: feature, style, 탭 컨테이너, 🌈FE

#255 대시보드의 z-index 추가
  cocode/src/components/Common/DropDownMenu/style.js
Labels: 🌈FE, 🐛bug

#256 다른 사람의 코코넛을 서버에 fork 요청하는 기능 구현
  cocode/src/actions/Project.js
  cocode/src/actions/types.js
  cocode/src/constants/keyCode.js
  cocode/src/containers/Project/Editor/index.js
  cocode/src/pages/Project/index.js
  cocode/src/pages/Project/parseProject.js
  cocode/src/pages/Version1/index.js
  cocode/src/reducers/ProjectReducer.js
  cocode/src/template/copyProject.js
  cocode/src/template/objectIdMapper.js
  cocode/src/template/react.js
  cocode/src/utils/keyDownEvent.js
Labels: feature, 🌈FE

#259 에러 페이지 작성
  cocode/src/App.js
  cocode/src/containers/NotFound/WeAreSorry/coconut.png
  cocode/src/containers/NotFound/WeAreSorry/index.js
  cocode/src/containers/NotFound/WeAreSorry/style.js
  cocode/src/pages/NotFound/index.js
  cocode/src/pages/index.js
Labels: style, 🌈FE

#260 Cocode와 coconut 분리 작업
  cocode/package.json
  cocode/src/App.js
  cocode/src/actions/Project.js
  cocode/src/actions/types.js
  cocode/src/bundler/require.js
  cocode/src/components/Project/BrowserV2/index.js
  cocode/src/components/Project/BrowserV2/style.js
  cocode/src/components/Project/DependencySearchItem/index.js
  cocode/src/config/index.js
  cocode/src/indexedDB/index.js
  cocode/src/pages/Coconut/index.js
  cocode/src/pages/Coconut/style.js
  cocode/src/pages/Project/getUpdatedPackageJSON.js
  cocode/src/pages/Project/index.js
  cocode/src/pages/index.js
  cocode/src/reducers/ProjectReducer.js
  cocode/webpack.config.js
  cocode/yarn.lock
Labels: 🌈FE

#279 Cocode 1.2.2를 위한 준비
  cocode/src/App.js
  cocode/src/actions/Project.js
  cocode/src/actions/types.js
  cocode/src/bundler/core.js
  cocode/src/bundler/global.js
  cocode/src/bundler/index.js
  cocode/src/bundler/pathParser.js
  cocode/src/bundler/require.js
  cocode/src/components/Project/BrowserV2/index.js
  cocode/src/indexedDB/index.js
  cocode/src/pages/Coconut/index.js
  cocode/src/pages/Coconut/style.js
  cocode/src/pages/index.js
  cocode/src/reducers/ProjectReducer.js
Labels: 🌈FE

#277 Coconut cocode에서 분리
  .travis.yml
  coconut/.commitlintrc.json
  coconut/.dockerignore
  coconut/.eslintignore
  coconut/.eslintrc.json
  coconut/.gitignore
  coconut/.prettierignore
  coconut/.prettierrc
  coconut/Dockerfile
  coconut/Dockerfile.dev
  coconut/README.md
  coconut/config-overrides.js
  coconut/dev.env
  coconut/nginx/conf.d/default.conf
  coconut/package.json
  coconut/public/favicon.ico
  coconut/public/index.html
  coconut/src/App.js
  coconut/src/App.test.js
  coconut/src/actions/API.js
  coconut/src/actions/Project.js
  coconut/src/actions/types.js
  coconut/src/apis/Dependency.js
  coconut/src/apis/Project.js
  coconut/src/bundler/core.js
  coconut/src/bundler/global.js
  coconut/src/bundler/index.js
  coconut/src/bundler/pathParser.js
  coconut/src/bundler/require.js
  coconut/src/components/Coconut/index.js
  coconut/src/components/Coconut/style.js
  coconut/src/components/CoconutSpinner/index.js
  coconut/src/components/CoconutSpinner/style.js
  coconut/src/components/Logo/index.js
  coconut/src/components/Logo/logo.svg
  coconut/src/components/TinyCoconutLogo/index.js
  coconut/src/config/index.js
  coconut/src/hooks/index.js
  coconut/src/hooks/useBuildProject.js
  coconut/src/hooks/useCommunicateCocode.js
  coconut/src/hooks/useConnectToIDB.js
  coconut/src/hooks/useFetch.js
  coconut/src/hooks/useUpdateDependency.js
  coconut/src/hooks/useUpdateProject.js
  coconut/src/index.js
  coconut/src/indexedDB/index.js
  coconut/src/reducers/APIReducer.js
  coconut/src/reducers/ProjectReducer.js
  coconut/src/setupTests.js
  coconut/src/utils/getUpdatedPackageJSON.js
  coconut/yarn.lock
  env.tar.enc
  script/update-env-files.sh
Labels: Refactoring, 🌈FE

#278 토스트 컴포넌트 구현
  cocode/public/index.html
  cocode/src/components/Common/Toast/ToastContainer.js
  cocode/src/components/Common/Toast/ToastItem.js
  cocode/src/components/Common/Toast/index.js
  cocode/src/components/Common/Toast/style.js
  cocode/src/components/Project/BrowserV2/index.js
  cocode/src/constants/statusCode.js
  cocode/src/constants/theme.js
  cocode/src/pages/Project/index.js
Labels: feature, style, 🌈FE

#281 fix: #269 코드 저장시 가입이 안되어있다고 뜨는 에러 해결
  cocode/src/containers/Project/Editor/index.js
  cocode/src/pages/Project/index.js
  cocode/src/pages/Project/parseProject.js
Labels: feature, 🌈FE, 🐛bug

#282 디펜던시 검색에 디바운스 기법 적용
  cocode/package.json
  cocode/src/components/Common/GlobalStyle/index.js
  cocode/src/components/Project/DependencySearch/index.js
  yarn.lock
Labels: feature, 🌈FE, 🐛bug

#280 Cocode 1.2.2
  cocode/package.json
  cocode/public/index.html
  cocode/src/App.js
  cocode/src/actions/Project.js
  cocode/src/actions/types.js
  cocode/src/bundler/core.js
  cocode/src/bundler/global.js
  cocode/src/bundler/index.js
  cocode/src/bundler/pathParser.js
  cocode/src/bundler/require.js
  cocode/src/components/Common/GlobalStyle/index.js
  cocode/src/components/Common/Toast/ToastContainer.js
  cocode/src/components/Common/Toast/ToastItem.js
  cocode/src/components/Common/Toast/index.js
  cocode/src/components/Common/Toast/style.js
  cocode/src/components/DashBoard/ProjectCard/index.js
  cocode/src/components/DashBoard/ProjectCard/style.js
  cocode/src/components/Project/BrowserV2/index.js
  cocode/src/components/Project/DependencySearch/index.js
  cocode/src/components/Project/Directory/index.js
  cocode/src/components/Project/File/index.js
  cocode/src/components/Project/NewFile/index.js
  cocode/src/constants/notificationMessage.js
  cocode/src/constants/statusCode.js
  cocode/src/constants/theme.js
  cocode/src/containers/Project/Editor/index.js
  cocode/src/containers/Project/InfoTab/index.js
  cocode/src/containers/Project/TabBar/index.js
  cocode/src/containers/Project/TabContainer/index.js
  cocode/src/indexedDB/index.js
  cocode/src/pages/Coconut/index.js
  cocode/src/pages/Coconut/style.js
  cocode/src/pages/DashBoard/index.js
  cocode/src/pages/DashBoard/style.js
  cocode/src/pages/Project/index.js
  cocode/src/pages/Project/parseProject.js
  cocode/src/pages/index.js
  cocode/src/reducers/ProjectReducer.js
  cocode/src/template/react.js
  yarn.lock
Labels: 배포💥

#287 라이브 서버 구축
  live-server/.gitignore
  live-server/.prettierrc
  live-server/app.js
  live-server/package.json
  live-server/yarn.lock
Labels: 👻BE

#288 라이브탭 및 인포 탭에 포크 기능 추가
  cocode/src/constants/notificationMessage.js
  cocode/src/containers/Project/Editor/index.js
  cocode/src/containers/Project/InfoTab/index.js
  cocode/src/containers/Project/LiveOffTab/index.js
  cocode/src/pages/Project/index.js
Labels: feature, 🌈FE, 🐛bug

#289 프로젝트 및 라이브 페이지에서 헤더 수정
  cocode/src/constants/theme.js
  cocode/src/containers/Common/Header/index.js
  cocode/src/containers/Common/Header/style.js
  cocode/src/pages/Live/index.js
  cocode/src/pages/Live/style.js
  cocode/src/pages/Project/index.js
  cocode/src/pages/Project/style.js
Labels: feature, style, 🌈FE

#293 라이브가 종료된 경우 토스트 노출
  cocode/src/constants/notificationMessage.js
  cocode/src/containers/Live/LiveOnTab/style.js
  cocode/src/pages/Live/index.js
Labels: feature, 🌈FE

#295 로그아웃 버그 수정
  cocode/src/App.js
  cocode/src/config/index.js
  cocode/src/containers/Common/Header/index.js
  cocode/src/containers/DashBoard/ProjectCardList/style.js
  cocode/src/utils/deleteCookie.js
Labels: feature, 🌈FE

#305 로그인 성공시 이전 페이지로 리다이렉트
  cocode/src/App.js
  cocode/src/components/Common/LoginModalBody/index.js
  cocode/src/components/Common/Modal/style.js
  cocode/src/containers/SignIn/index.js
  cocode/src/containers/SignIn/style.js
  cocode/src/pages/DashBoard/index.js
  cocode/src/pages/Empty/index.js
  cocode/src/pages/Live/index.js
  cocode/src/pages/index.js
Labels: feature, 🌈FE

#309 브라우저에 주소 표시줄 노출
  cocode/src/components/Project/BrowserV2/index.js
  cocode/src/components/Project/BrowserV2/search.svg
  cocode/src/components/Project/BrowserV2/style.js
  cocode/src/constants/theme.js
Labels: feature, style, 🌈FE

#314 라이브에 참여한 유저의 커서 색 구분
  cocode/src/constants/cursorColors.js
  cocode/src/containers/Live/Editor/index.js
  cocode/src/utils/monacoWidget.js
Labels: feature, 🌈FE
